version: 2

sources:
  - name: brazilian  # Name of the Dataset
    database: fluid-keyword-454503-a8

    tables:
      - name: geolocation
        columns:
          - name: geolocation_zip_code_prefix
            description: Primary Key
          - name: geolocation_lat
          - name: geolocation_lng
          - name: geolocation_city
          - name: geolocation_state

      - name: customers_dataset
        columns:
          - name: customer_id
            description: Primary Key
          - name: customer_unique_id
          - name: customer_zip_code_prefix
          - name: customer_city
          - name: customer_state

      - name: sellers
        columns:
          - name: seller_id
            description: Primary Key
          - name: seller_zip_code_prefix
          - name: seller_city
          - name: seller_state

      - name: product_translation
        columns:
          - name: string_field_0 #product_category_name
            description: product_category_name 
          - name: string_field_1 #product_category_name_english
          - name: product_category

      - name: products
        columns:
          - name: product_id
            description: Primary Key
          - name: product_category_name
            description: Foreign Key >- product_translation.string_field_0
          - name: product_name_lenght
          - name: product_description_lenght
          - name: product_photos_qty
          - name: product_weight_g
          - name: product_length_cm
          - name: product_height_cm
          - name: product_width_cm

      - name: orders
        columns:
          - name: order_id
            description: Primary Key
          - name: customer_id
            description: Foreign Key >- customers.customer_id
          - name: order_status
          - name: order_purchase_timestamp
          - name: order_approved_at
          - name: order_delivered_carrier_date
          - name: order_delivered_customer_date
          - name: order_estimated_delivery_date

      - name: order_reviews
        columns:
          - name: review_id
            description: Primary Key
          - name: order_id
            description: Foreign Key >- orders.order_id
          - name: review_score
          - name: review_comment_title
          - name: review_comment_message
          - name: review_creation_date
          - name: review_answer_timestamp

      - name: order_items
        columns:
          - name: order_id
            description: Foreign Key >- orders.order_id
          - name: order_item_id
          - name: product_id
            description: Foreign Key >- products.product_id
          - name: seller_id
            description: Foreign Key >- sellers.seller_id
          - name: shipping_limit_date
          - name: price
          - name: freight_value

      - name: order_payments
        columns:
          - name: order_id
            description: Foreign Key >- orders.order_id
          - name: payment_sequential
          - name: payment_type
          - name: payment_installments
          - name: payment_value
